export class Mod {
    id: number;
    game_id: number;
    status: number;
    visible: number;
    submitter_id: number;
    submitter_name_id: string;
    submitter_username: string;
    submitter_date_online: number;
    submitter_date_joined: number;
    submitter_avatar_filename: string;
    submitter_avatar_original: string;
    submitter_avatar_50x50: string;
    submitter_avatar_100x100: string;
    submitter_timezone: string;
    submitter_language: string;
    submitter_profile_url: string;
    date_added: number;
    date_updated: number;
    date_live: number;
    maturity_option: number;
    community_options: number;
    monetisation_options: number;
    price: number;
    tax: number;
    logo_filename: string;
    logo_original: string;
    logo_320x180: string;
    logo_640x360: string;
    logo_1280x720: string;
    homepage_url: string;
    name: string;
    name_id: string;
    summary: string;
    description: string;
    description_plaintext: string;
    metadata_blob: string;
    mod_url: string;
    youtube_media: Array<string>;
    sketchfab_media: Array<string>;
    images: Array<object>;
    tags: Array<object>;
    popularity_rank_position: number;
    popularity_rank_total_mods: number;
    downloads_today: number;
    downloads_total: number;
    subscribers_total: number;
    ratings_total: number;
    ratings_positive: number;
    ratings_negative: number;
    ratings_display_text: string;
    constructor(tbl) {
        const submitter = tbl.submitted_by;
        this.id = tbl.id;
        this.game_id = tbl.game_id;
        this.status = tbl.status;
        this.visible = tbl.visible;
        this.submitter_id = submitter.id;
        this.submitter_name_id = submitter.name_id;
        this.submitter_username = submitter.username;
        this.submitter_date_online = submitter.date_online;
        this.submitter_date_joined = submitter.date_joined;
        this.submitter_avatar_filename = submitter.avatar.filename;
        this.submitter_avatar_original = submitter.avatar.original;
        this.submitter_avatar_50x50 = submitter.avatar.thumb_50x50;
        this.submitter_avatar_100x100 = submitter.avatar.thumb_100x100;
        this.submitter_timezone = submitter.timezone;
        this.submitter_language = submitter.language;
        this.submitter_profile_url = submitter.profile_url;
        this.date_added = tbl.date_added;
        this.date_updated = tbl.date_updated;
        this.date_live = tbl.date_live;
        this.maturity_option = tbl.maturity_option;
        this.community_options = tbl.community_options;
        this.monetisation_options = tbl.monetisation_options;
        this.price = tbl.price;
        this.tax = tbl.tax;
        this.logo_filename = tbl.logo.filename;
        this.logo_original = tbl.logo.original;
        this.logo_320x180 = tbl.logo.thumb_320x180;
        this.logo_640x360 = tbl.logo.thumb_640x360;
        this.logo_1280x720 = tbl.logo.thumb_1280x720;
        this.homepage_url = tbl.homepage_url;
        this.name = tbl.name;
        this.name_id = tbl.name_id;
        this.summary = tbl.summary;
        this.description = tbl.description;
        this.description_plaintext = tbl.description_plaintext;
        this.metadata_blob = tbl.metadata_blob;
        this.mod_url = tbl.profile_url;
        this.youtube_media = tbl.media.youtube;
        this.sketchfab_media = tbl.media.sketchfab;
        this.images = tbl.media.images;
        this.popularity_rank_position = tbl.modfile.popularity_rank_position;
        this.popularity_rank_total_mods = tbl.modfile.popularity_rank_total_mods;
        this.downloads_today = tbl.modfile.downloads_today;
        this.downloads_total = tbl.modfile.downloads_total;
        this.subscribers_total = tbl.modfile.subscribers_total;
        this.ratings_total = tbl.modfile.ratings_total;
        this.ratings_positive = tbl.modfile.ratings_positive;
        this.ratings_negative = tbl.modfile.ratings_negative;
        this.ratings_display_text = tbl.modfile.ratings_display_text;
    }
}
