import * as interfaces from './interfaces';
export declare class Game {
    id: number;
    status: number;
    submitted_by: interfaces.submitter;
    date_added: number;
    date_updated: number;
    date_live: number;
    presentation_option: number;
    community_options: number;
    monetisation_options: number;
    submission_option: number;
    curation_option: number;
    revenue_options: number;
    api_access_options: number;
    maturity_options: number;
    ugc_name: string;
    icon: interfaces.icon;
    logo: interfaces.logo;
    header: interfaces.header;
    name: string;
    name_id: string;
    summary: string;
    instructions_url: string;
    profile_url: string;
    other_urls: Array<interfaces.other_url>;
    tag_options: Array<interfaces.tag_option>;
    stats: interfaces.stats;
    theme: interfaces.theme;
    platforms: Array<interfaces.platform>;
    constructor(tbl: any);
}
